/** Eventos Socket.IO – TalkApp (conversaciones) */
module.exports = {
  SET_USER: 'set_user',
  JOIN_CONVERSATION: 'join_conversation',
  JOIN_CONVERSATION_ROOMS: 'join_conversation_rooms',
  LEAVE_CONVERSATION: 'leave_conversation',
  SEND_MESSAGE: 'send_message',
  REACT_TO_MESSAGE: 'react_to_message',
  MARK_CONVERSATION_READ: 'mark_conversation_read',
  MESSAGE_DELIVERED: 'message_delivered',
  REFRESH_ONLINE_LIST: 'refresh_online_list',
  VIDEO_CALL_OFFER: 'video_call_offer',
  VIDEO_CALL_ANSWER: 'video_call_answer',
  VIDEO_CALL_REJECT: 'video_call_reject',
  VIDEO_CALL_CANCEL: 'video_call_cancel',

  NEW_MESSAGE: 'new_message',
  MESSAGE_UPDATED: 'message_updated',
  MESSAGE_DELETED: 'message_deleted',
  NOTIFY_MESSAGE_DELETED: 'notify_message_deleted',
  USERS_ONLINE: 'users_online',
  USER_LAST_SEEN_UPDATED: 'user_last_seen_updated',
  CONVERSATION_PRESENCE: 'conversation_presence',
  CONVERSATION_HISTORY: 'conversation_history',
  VIDEO_CALL_INCOMING: 'video_call_incoming',
  VIDEO_CALL_ACCEPTED: 'video_call_accepted',
  VIDEO_CALL_REJECTED: 'video_call_rejected',
  VIDEO_CALL_CANCELLED: 'video_call_cancelled',
  USER_PROFILE_UPDATED: 'user_profile_updated',
  USER_TYPING: 'user_typing',
  USER_STOPPED_TYPING: 'user_stopped_typing',
  CONVERSATION_UPDATED: 'conversation_updated',
};
