export const SOCKET_EVENTS = {
  SET_USER: 'set_user',
  JOIN_CHAT: 'join_chat',
  JOIN_CHAT_ROOMS: 'join_chat_rooms',
  LEAVE_CHAT: 'leave_chat',
  SEND_MESSAGE: 'send_message',
  REACT_TO_MESSAGE: 'react_to_message',
  EDIT_MESSAGE: 'edit_message',
  PIN_MESSAGE: 'pin_message',
  UNPIN_MESSAGE: 'unpin_message',
  MARK_CHAT_READ: 'mark_chat_read',
  REFRESH_ONLINE_LIST: 'refresh_online_list',
  VIDEO_CALL_OFFER: 'video_call_offer',
  VIDEO_CALL_ANSWER: 'video_call_answer',
  VIDEO_CALL_REJECT: 'video_call_reject',
  VIDEO_CALL_CANCEL: 'video_call_cancel',

  NEW_MESSAGE: 'new_message',
  MESSAGE_UPDATED: 'message_updated',
  MESSAGE_DELETED: 'message_deleted',
  NOTIFY_MESSAGE_DELETED: 'notify_message_deleted',
  USERS_ONLINE: 'users_online',
  USER_LAST_SEEN_UPDATED: 'user_last_seen_updated',
  CHAT_PRESENCE: 'chat_presence',
  CHAT_HISTORY: 'chat_history',
  VIDEO_CALL_INCOMING: 'video_call_incoming',
  VIDEO_CALL_ACCEPTED: 'video_call_accepted',
  VIDEO_CALL_REJECTED: 'video_call_rejected',
  VIDEO_CALL_CANCELLED: 'video_call_cancelled',
  USER_PROFILE_UPDATED: 'user_profile_updated',
} as const
